project:
  type: website

website:
  title: "Documentation Menu"
  navbar:
    background: secondary
    style: "floating"
    search: true    
    left:
      - href: index.qmd
        text: Home
      - href : class_notes/clases.qmd
        text: Clases
      - href: labs/labs.qmd
        text: Labs
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    ###
    toc-depth: 5
    email-obfuscation: javascript
    smooth-scroll: true
    #backgroundcolor: black
    code-link: true
    #code-block-bg: "#29465B"
    code-line-numbers: "true"
    code-overflow: "wrap" 

###
execute:
  cache: true
  freeze: true



highlight-style: breezedark


