project:
  type: website

website:
  title: "Documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href : class_notes/clases.qmd
        text: Clases
      - href: labs/labs.qmd
        text: Labs
      - about.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



